### ISSUE TITLE
Status(StatusCode=Unknown, Detail="Exception was thrown by handler.

### ISSUE THREAD

**Issue by forconz** [michal-panfil/RealTimePriceGRPC#1]
I download zip, and build the code by vs 2019,  

I frist run the PriceGrpcService

I only modified the code of gRPCClient
`var channel = GrpcChannel.ForAddress("https://localhost:44374");`

I ran your repo and I get RpcException:
Grpc.Core.RpcException:“Status(StatusCode=Unknown, Detail="Exception was thrown by handler.")”

   at Grpc.Net.Client.Internal.HttpContentClientStreamReader`2.<MoveNextCore>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at gRPCClient.Program.<Main>d__0.MoveNext() in C:\Users\Tao\Downloads\RealTimePriceGRPC-master\RealTimePriceGRPC-master\gRPCClient\Program.cs:line 19

How can I do?

**Comment by forconz** [comment]
Startup.cs
```
services.AddGrpc(options => options.EnableDetailedErrors = true);

```

Grpc.Core.RpcException:“Status(StatusCode="Unknown", Detail="Exception was thrown by handler. InvalidOperationException: Unable to resolve service for type 'PriceGrpcService.Models.IDataDownloader' while attempting to activate 'PriceGrpcService.Services.PriceService'.")”

Startup.cs
```
services.AddSingleton<IDataDownloader, PageDownloader>();
services.AddSingleton<IDataParser, PageParser>();
```

The projects are work well.

**Comment by michal-panfil** [comment]
Thanks @forconz  for letting me know.
